repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(ya?ml|md)$
        args: [--write]

  - repo: local
    hooks:
      - id: terraform_fmt
        name: terraform fmt
        entry: terraform fmt -recursive
        language: system
        files: \.tf$
        exclude: \.terraform/
        pass_filenames: false

      - id: terraform_validate
        name: terraform validate
        entry: terraform validate
        language: system
        files: \.tf$
        exclude: \.terraform/
        pass_filenames: false

      - id: tflint
        name: tflint
        entry: tflint --recursive
        language: golang
        additional_dependencies:
          - github.com/terraform-linters/tflint@v0.54.0
        files: \.tf$
        exclude: \.terraform/
        pass_filenames: false

      - id: kubeconform
        name: kubeconform linter
        entry: kubeconform -summary -strict -ignore-missing-schemas -skip CustomResourceDefinition
        language: golang
        additional_dependencies:
          - github.com/yannh/kubeconform/cmd/kubeconform@v0.7.0
        files: \.ya?ml$
        exclude: ^(\.pre-commit-config\.yaml|\.github/)
