apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - databases/daylog
  - apps/daylog
  - configs/argocd
  # Note: argocd/application-homelab.yaml is applied manually (bootstrap)
