apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configs/external-secrets/clustersecretstore-azure-key-vault.yaml
  - databases/daylog
  - apps/daylog
  - argocd/application-homelab.yaml
