apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: daylog
resources:
  - externalsecret-daylog-pgadmin-credentials.yaml
  - pvc-daylog-pgadmin.yaml
  - deployment-daylog-pgadmin.yaml
  - service-daylog-pgadmin.yaml
