apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azure-config
  namespace: daylog
  labels:
    app: daylog
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-key-vault-store
    kind: ClusterSecretStore
  target:
    name: azure-config
    template:
      type: Opaque
  data:
    - secretKey: tenant-id
      remoteRef:
        key: azure-tenant-id
    - secretKey: key-vault-name
      remoteRef:
        key: azure-key-vault-name
