apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: daylog
resources:
  - serviceaccount-automation.yaml
  - externalsecret-azure-config.yaml
  - externalsecret-azure-creds.yaml
  - cronjob-garmin-sync.yaml
  - cronjob-withings-sync.yaml
  - job-garmin-sync-annual.yaml
  - job-withings-sync-annual.yaml
